# Imports

In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Load dataset

In [2]:
df = pd.read_csv('../datasets/train.csv')

# Data preparation

In [3]:
# vizualizar o dataset
df.head()

id_cliente  idade  saldo_atual  divida_atual  renda_anual  \
0        1767     21   278.172008       2577.05  24196.89636   
1       11920     40   268.874152       2465.39  19227.37796   
2        8910     36   446.643127       1055.29  42822.28223   
3        4964     58   321.141267        703.05  51786.82600   
4       10100     35   428.716114        891.29  44626.85346   

   valor_em_investimentos  taxa_utilizacao_credito  num_emprestimos  \
0              104.306544                31.038763                6   
1               69.858778                36.917093                5   
2              134.201478                34.561714                0   
3              297.350067                31.493561                0   
4              134.201478                28.028887                2   

   num_contas_bancarias  num_cartoes_credito  dias_atraso_dt_venc  \
0                     5                    7                   21   
1                     8                    5                   40   
2                     3                    6                   26   
3                     3                    7                   12   
4                     8                    7                   24   

   num_pgtos_atrasados  num_consultas_credito  taxa_juros investe_exterior  \
0                   14                      9          15              Não   
1                   23                     10          18              Não   
2                   13                      3          15              Sim   
3                    7                      2           1              Sim   
4                   10                      8          20              Sim   

  pessoa_polit_exp limite_adicional  
0              Não            Negar  
1              Não            Negar  
2              Não            Negar  
3              Não            Negar  
4              Não            Negar

In [4]:
# Separar as features dos labels
features = ['idade', 'divida_atual', 'renda_anual', 'valor_em_investimentos', 
            'taxa_utilizacao_credito', 'num_emprestimos', 'num_contas_bancarias',
            'num_cartoes_credito', 'dias_atraso_dt_venc', 'num_pgtos_atrasados',
            'num_consultas_credito', 'taxa_juros',]

label = ['saldo_atual']

In [5]:
# Criar as variáveis para treinamento do Modelo
x_train = df.loc[:, features]
y_train = df.loc[:, label]

# Model Training

In [8]:
# Model Definition
lr_model = LinearRegression()

# Model Fit (Ajuste, Treinamento)
lr_model.fit(x_train, y_train)

# Previsão
y_pred = lr_model.predict(x_train)

In [7]:
# Dentro de lr_model está armazenado os coeficientes calculado pelo método dos mínimos quadrados
lr_model.coef_

array([[ 3.96706202e-04, -4.00595601e-02,  2.77622532e-06,
        -1.04318668e-03,  9.80890872e+00, -1.22353405e-02,
        -6.33015538e-03, -3.57808095e-03, -2.15858165e+00,
         3.77570060e-04,  6.79176336e-03,  3.48471845e-03]])

In [13]:
#  Dentro de lr_model tambem esta armazenado o intercepto
lr_model.intercept_

array([190.82359144])

In [9]:
# Incluir a Predicao em um base para analise
df1 = df.loc[:, ['id_cliente', 'saldo_atual']]
df1['predicted'] = y_pred

df1.head()

id_cliente  saldo_atual   predicted
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

In [12]:
# Montar o calculo da predicao do primeiro cliente de df1
np.sum((x_train.loc[0,].values * lr_model.coef_)) + lr_model.intercept_

array([346.66954862])

In [14]:
# Montar o calculo da predicao para os primeiros 10 clientes de df1
for i in range(len(x_train)):
    print(np.sum((x_train.loc[i,].values * lr_model.coef_)) + lr_model.intercept_)
    
    if i == 10:
        break

[346.66954862]
[367.84027655]
[431.46897895]
[445.50646329]
[378.27116865]
[352.4833463]
[410.60408532]
[210.68563909]
[388.61996465]
[301.1477063]
[158.0964866]


# Performance